[server]
address = "localhost"
port = 8000
folderWatchBlacklist = ["morpher/__pycache__"]
enableXsrfProtection=false
enableCORS = false
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base="light"
